language: cpp
compiler: gcc

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
    - make
    - git ls-files src/ | xargs clang-format -i && git diff --exit-code
    - git ls-files test/ | xargs clang-format -i && git diff --exit-code